-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHsTLZks/4RSt9UFi
Cwgs2vHtPSqBMIxIxozQDWdihNugCgYIKoZIzj0DAQehRANCAAR1nQN0kdoExGpG
WY6SoEFzq8ABrZeTbAoS2dPaXb4AosE12zw3R7lUxlMeyLcynLn1sV71BOElQ5Zi
jpSmTp5y
-----END PRIVATE KEY-----